package mocks

import (
	"context"

	"github.com/sainaif/animalsys/backend/internal/domain/entities"
	"github.com/sainaif/animalsys/backend/internal/domain/repositories"
	"github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CampaignRepository is an autogenerated mock type for the CampaignRepository type
type CampaignRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, campaign
func (_m *CampaignRepository) Create(ctx context.Context, campaign *entities.Campaign) error {
	ret := _m.Called(ctx, campaign)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Campaign) error); ok {
		r0 = rf(ctx, campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CampaignRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureIndexes provides a mock function with given fields: ctx
func (_m *CampaignRepository) EnsureIndexes(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *CampaignRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*entities.Campaign, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entities.Campaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveCampaigns provides a mock function with given fields: ctx
func (_m *CampaignRepository) GetActiveCampaigns(ctx context.Context) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignStatistics provides a mock function with given fields: ctx
func (_m *CampaignRepository) GetCampaignStatistics(ctx context.Context) (*repositories.CampaignStatistics, error) {
	ret := _m.Called(ctx)

	var r0 *repositories.CampaignStatistics
	if rf, ok := ret.Get(0).(func(context.Context) *repositories.CampaignStatistics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.CampaignStatistics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignsByManager provides a mock function with given fields: ctx, managerID
func (_m *CampaignRepository) GetCampaignsByManager(ctx context.Context, managerID primitive.ObjectID) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx, managerID)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*entities.Campaign); ok {
		r0 = rf(ctx, managerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, managerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeaturedCampaigns provides a mock function with given fields: ctx
func (_m *CampaignRepository) GetFeaturedCampaigns(ctx context.Context) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicCampaigns provides a mock function with given fields: ctx
func (_m *CampaignRepository) GetPublicCampaigns(ctx context.Context) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *CampaignRepository) List(ctx context.Context, filter *repositories.CampaignFilter) ([]*entities.Campaign, int64, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CampaignFilter) []*entities.Campaign); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *repositories.CampaignFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *repositories.CampaignFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, campaign
func (_m *CampaignRepository) Update(ctx context.Context, campaign *entities.Campaign) error {
	ret := _m.Called(ctx, campaign)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Campaign) error); ok {
		r0 = rf(ctx, campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCampaignStats provides a mock function with given fields: ctx, campaignID, donationAmount, isNewDonor
func (_m *CampaignRepository) UpdateCampaignStats(ctx context.Context, campaignID primitive.ObjectID, donationAmount float64, isNewDonor bool) error {
	ret := _m.Called(ctx, campaignID, donationAmount, isNewDonor)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, float64, bool) error); ok {
		r0 = rf(ctx, campaignID, donationAmount, isNewDonor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
