package mocks

import (
	"context"
	"time"

	"github.com/sainaif/animalsys/backend/internal/domain/entities"
	"github.com/sainaif/animalsys/backend/internal/domain/repositories"
	"github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// DonationRepository is an autogenerated mock type for the DonationRepository type
type DonationRepository struct {
	mock.Mock
}

// AggregateDonorsByCampaignID provides a mock function with given fields: ctx, campaignID, limit, offset
func (_m *DonationRepository) AggregateDonorsByCampaignID(ctx context.Context, campaignID primitive.ObjectID, limit int64, offset int64) ([]*repositories.DonorAggregationResult, int64, error) {
	ret := _m.Called(ctx, campaignID, limit, offset)

	var r0 []*repositories.DonorAggregationResult
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int64, int64) []*repositories.DonorAggregationResult); ok {
		r0 = rf(ctx, campaignID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repositories.DonorAggregationResult)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, int64, int64) int64); ok {
		r1 = rf(ctx, campaignID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, primitive.ObjectID, int64, int64) error); ok {
		r2 = rf(ctx, campaignID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Create provides a mock function with given fields: ctx, donation
func (_m *DonationRepository) Create(ctx context.Context, donation *entities.Donation) error {
	ret := _m.Called(ctx, donation)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Donation) error); ok {
		r0 = rf(ctx, donation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DonationRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureIndexes provides a mock function with given fields: ctx
func (_m *DonationRepository) EnsureIndexes(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *DonationRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*entities.Donation, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entities.Donation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Donation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCampaignID provides a mock function with given fields: ctx, campaignID
func (_m *DonationRepository) GetByCampaignID(ctx context.Context, campaignID primitive.ObjectID) ([]*entities.Donation, error) {
	ret := _m.Called(ctx, campaignID)

	var r0 []*entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*entities.Donation); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDonorID provides a mock function with given fields: ctx, donorID
func (_m *DonationRepository) GetByDonorID(ctx context.Context, donorID primitive.ObjectID) ([]*entities.Donation, error) {
	ret := _m.Called(ctx, donorID)

	var r0 []*entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*entities.Donation); ok {
		r0 = rf(ctx, donorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, donorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDonationStatistics provides a mock function with given fields: ctx
func (_m *DonationRepository) GetDonationStatistics(ctx context.Context) (*repositories.DonationStatistics, error) {
	ret := _m.Called(ctx)

	var r0 *repositories.DonationStatistics
	if rf, ok := ret.Get(0).(func(context.Context) *repositories.DonationStatistics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.DonationStatistics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDonationsByDateRange provides a mock function with given fields: ctx, from, to
func (_m *DonationRepository) GetDonationsByDateRange(ctx context.Context, from time.Time, to time.Time) ([]*entities.Donation, error) {
	ret := _m.Called(ctx, from, to)

	var r0 []*entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []*entities.Donation); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingThankYous provides a mock function with given fields: ctx
func (_m *DonationRepository) GetPendingThankYous(ctx context.Context) ([]*entities.Donation, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Donation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecurringDonations provides a mock function with given fields: ctx
func (_m *DonationRepository) GetRecurringDonations(ctx context.Context) ([]*entities.Donation, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Donation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *DonationRepository) List(ctx context.Context, filter *repositories.DonationFilter) ([]*entities.Donation, int64, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*entities.Donation
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.DonationFilter) []*entities.Donation); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donation)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *repositories.DonationFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *repositories.DonationFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, donation
func (_m *DonationRepository) Update(ctx context.Context, donation *entities.Donation) error {
	ret := _m.Called(ctx, donation)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Donation) error); ok {
		r0 = rf(ctx, donation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
