package mocks

import (
	"context"

	"github.com/sainaif/animalsys/backend/internal/domain/entities"
	"github.com/sainaif/animalsys/backend/internal/domain/repositories"
	"github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// DonorRepository is an autogenerated mock type for the DonorRepository type
type DonorRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, donor
func (_m *DonorRepository) Create(ctx context.Context, donor *entities.Donor) error {
	ret := _m.Called(ctx, donor)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Donor) error); ok {
		r0 = rf(ctx, donor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DonorRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureIndexes provides a mock function with given fields: ctx
func (_m *DonorRepository) EnsureIndexes(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *DonorRepository) FindByEmail(ctx context.Context, email string) (*entities.Donor, error) {
	ret := _m.Called(ctx, email)

	var r0 *entities.Donor
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Donor); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Donor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *DonorRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*entities.Donor, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.Donor
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entities.Donor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Donor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindManyByIDs provides a mock function with given fields: ctx, ids
func (_m *DonorRepository) FindManyByIDs(ctx context.Context, ids []primitive.ObjectID) ([]*entities.Donor, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*entities.Donor
	if rf, ok := ret.Get(0).(func(context.Context, []primitive.ObjectID) []*entities.Donor); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []primitive.ObjectID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDonorStatistics provides a mock function with given fields: ctx
func (_m *DonorRepository) GetDonorStatistics(ctx context.Context) (*repositories.DonorStatistics, error) {
	ret := _m.Called(ctx)

	var r0 *repositories.DonorStatistics
	if rf, ok := ret.Get(0).(func(context.Context) *repositories.DonorStatistics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.DonorStatistics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLapsedDonors provides a mock function with given fields: ctx, days
func (_m *DonorRepository) GetLapsedDonors(ctx context.Context, days int) ([]*entities.Donor, error) {
	ret := _m.Called(ctx, days)

	var r0 []*entities.Donor
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entities.Donor); ok {
		r0 = rf(ctx, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMajorDonors provides a mock function with given fields: ctx
func (_m *DonorRepository) GetMajorDonors(ctx context.Context) ([]*entities.Donor, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Donor
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Donor); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *DonorRepository) List(ctx context.Context, filter *repositories.DonorFilter) ([]*entities.Donor, int64, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*entities.Donor
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.DonorFilter) []*entities.Donor); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Donor)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *repositories.DonorFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *repositories.DonorFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, donor
func (_m *DonorRepository) Update(ctx context.Context, donor *entities.Donor) error {
	ret := _m.Called(ctx, donor)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Donor) error); ok {
		r0 = rf(ctx, donor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
