package mocks

import (
	"context"

	"github.com/sainaif/animalsys/backend/internal/domain/entities"
	"github.com/sainaif/animalsys/backend/internal/domain/repositories"
	"github.com/sainaif/animalsys/backend/internal/usecase/campaign"
	"github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CampaignUseCase is an autogenerated mock type for the ICampaignUseCase type
type CampaignUseCase struct {
	mock.Mock
}

// ActivateCampaign provides a mock function with given fields: ctx, id, userID
func (_m *CampaignUseCase) ActivateCampaign(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelCampaign provides a mock function with given fields: ctx, id, userID
func (_m *CampaignUseCase) CancelCampaign(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteCampaign provides a mock function with given fields: ctx, id, userID
func (_m *CampaignUseCase) CompleteCampaign(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCampaign provides a mock function with given fields: ctx, _a1, userID
func (_m *CampaignUseCase) CreateCampaign(ctx context.Context, _a1 *entities.Campaign, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, _a1, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Campaign, primitive.ObjectID) error); ok {
		r0 = rf(ctx, _a1, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCampaign provides a mock function with given fields: ctx, id, userID
func (_m *CampaignUseCase) DeleteCampaign(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveCampaigns provides a mock function with given fields: ctx
func (_m *CampaignUseCase) GetActiveCampaigns(ctx context.Context) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaign provides a mock function with given fields: ctx, id
func (_m *CampaignUseCase) GetCampaign(ctx context.Context, id primitive.ObjectID) (*entities.Campaign, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entities.Campaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignDonors provides a mock function with given fields: ctx, id, limit, offset
func (_m *CampaignUseCase) GetCampaignDonors(ctx context.Context, id primitive.ObjectID, limit int64, offset int64) ([]*campaign.CampaignDonor, int64, error) {
	ret := _m.Called(ctx, id, limit, offset)

	var r0 []*campaign.CampaignDonor
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, int64, int64) []*campaign.CampaignDonor); ok {
		r0 = rf(ctx, id, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*campaign.CampaignDonor)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, int64, int64) int64); ok {
		r1 = rf(ctx, id, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, primitive.ObjectID, int64, int64) error); ok {
		r2 = rf(ctx, id, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCampaignProgress provides a mock function with given fields: ctx, id
func (_m *CampaignUseCase) GetCampaignProgress(ctx context.Context, id primitive.ObjectID) (*campaign.CampaignProgress, error) {
	ret := _m.Called(ctx, id)

	var r0 *campaign.CampaignProgress
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *campaign.CampaignProgress); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*campaign.CampaignProgress)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignStatistics provides a mock function with given fields: ctx
func (_m *CampaignUseCase) GetCampaignStatistics(ctx context.Context) (*repositories.CampaignStatistics, error) {
	ret := _m.Called(ctx)

	var r0 *repositories.CampaignStatistics
	if rf, ok := ret.Get(0).(func(context.Context) *repositories.CampaignStatistics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.CampaignStatistics)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignsByManager provides a mock function with given fields: ctx, managerID
func (_m *CampaignUseCase) GetCampaignsByManager(ctx context.Context, managerID primitive.ObjectID) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx, managerID)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []*entities.Campaign); ok {
		r0 = rf(ctx, managerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, managerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeaturedCampaigns provides a mock function with given fields: ctx
func (_m *CampaignUseCase) GetFeaturedCampaigns(ctx context.Context) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicCampaigns provides a mock function with given fields: ctx
func (_m *CampaignUseCase) GetPublicCampaigns(ctx context.Context) ([]*entities.Campaign, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Campaign); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCampaigns provides a mock function with given fields: ctx, filter
func (_m *CampaignUseCase) ListCampaigns(ctx context.Context, filter *repositories.CampaignFilter) ([]*entities.Campaign, int64, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*entities.Campaign
	if rf, ok := ret.Get(0).(func(context.Context, *repositories.CampaignFilter) []*entities.Campaign); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Campaign)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, *repositories.CampaignFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *repositories.CampaignFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PauseCampaign provides a mock function with given fields: ctx, id, userID
func (_m *CampaignUseCase) PauseCampaign(ctx context.Context, id primitive.ObjectID, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShareCampaign provides a mock function with given fields: ctx, id
func (_m *CampaignUseCase) ShareCampaign(ctx context.Context, id primitive.ObjectID) (*campaign.CampaignShareable, error) {
	ret := _m.Called(ctx, id)

	var r0 *campaign.CampaignShareable
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *campaign.CampaignShareable); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*campaign.CampaignShareable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCampaign provides a mock function with given fields: ctx, _a1, userID
func (_m *CampaignUseCase) UpdateCampaign(ctx context.Context, _a1 *entities.Campaign, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, _a1, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Campaign, primitive.ObjectID) error); ok {
		r0 = rf(ctx, _a1, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCampaignAmount provides a mock function with given fields: ctx, id, amount, userID
func (_m *CampaignUseCase) UpdateCampaignAmount(ctx context.Context, id primitive.ObjectID, amount float64, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, id, amount, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, float64, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id, amount, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
